@startuml
title **Dynamic metadata matcher**\n<size:12><&chevron-right>matchIfMissing=false\n<size:12><&chevron-right>service1 using service2
skinparam interface {
  backgroundColor<<use case 1>> #C0504D
  fontColor<<use case 1>> #C0504D
  borderColor<<use case 1>> #C0504D
  backgroundColor<<use case 2>> #9BBB59
  fontColor<<use case 2>> #9BBB59
  borderColor<<use case 2>> #9BBB59
  backgroundColor<<use case 3>> #4BACC6
  fontColor<<use case 3>> #4BACC6
  borderColor<<use case 3>> #4BACC6
  backgroundColor<<use case 4>> Magenta
  fontColor<<use case 4>> Magenta
  borderColor<<use case 4>> Magenta
}
skinparam component {
  ArrowColor<<use case 1>> #C0504D
  ArrowLollipopColor<<use case 1>> #C0504D
  ArrowFontColor<<use case 1>> #C0504D
  ArrowColor<<use case 2>> #9BBB59
  ArrowFontColor<<use case 2>> #9BBB59
  ArrowColor<<use case 3>> #4BACC6
  ArrowFontColor<<use case 3>> #4BACC6
  ArrowColor<<use case 4>> Magenta
  ArrowFontColor<<use case 4>> Magenta
}

cloud "cloud"{
  [service1] as service11
  component service21 [service2
    eureka.instance.metadataMap.matcher-key=target1
  ]
  component service22 [service2
    eureka.instance.metadataMap.matcher-key=target2
  ]
}

() "error" as error

() "service1 code snippet:\ncurrent().put('dynamic-matcher-key','matcher-key');\ncurrent().put('matcher-key','target1');\nservice2.doSomething();" as request1 <<use case 1>>
request1 -down-> service11 <<use case 1>>
service11 -down-> service21 <<use case 1>>

() "service1 code snippet:\ncurrent().put('dynamic-matcher-key','matcher-key');\ncurrent().put('matcher-key','target2');\nservice2.doSomething();" as request2 <<use case 2>>
request2 -down-> service11 <<use case 2>>
service11 -down-> service22 <<use case 2>>

() "service1 code snippet:\nservice2.doSomething();" as request3 <<use case 3>>
request3 -down-> service11 <<use case 3>>
service11 -down-> error <<use case 3>>

() "service1 code snippet:\ncurrent().put('dynamic-matcher-key','matcher-key');\ncurrent().put('matcher-key','target3');\nservice2.doSomething();" as request4 <<use case 4>>
request4 -left-> service11 <<use case 4>>
service11 -down-> error <<use case 4>>
@enduml