server:
  port: 8000
  ssl:
    enabled: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  application:
    name: eureka
    default-domain: eureka
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false

endpoints:
  jmx:
    enabled: false
    domain: eureka
  env:
    enabled: false

eureka:
  client:
    enabled: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    metadataMap:
      instanceId: eureka
      zone: default


